nopCommerce_4.20_Source/src/Presentation/Nop.Web/Areas/Admin/Controllers/CustomerRoleController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Services.Catalog;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Customers;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class CustomerRoleController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerActivityService _customerActivityService;
        private readonly ICustomerRoleModelFactory _customerRoleModelFactory;
        private readonly ICustomerService _customerService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IProductService _productService;
        private readonly IWorkContext _workContext;

        #endregion

        #region Ctor

        public CustomerRoleController(ICustomerActivityService customerActivityService,
            ICustomerRoleModelFactory customerRoleModelFactory,
            ICustomerService customerService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IProductService productService,
            IWorkContext workContext)
        {
            _customerActivityService = customerActivityService;
            _customerRoleModelFactory = customerRoleModelFactory;
            _customerService = customerService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _productService = productService;
            _workContext = workContext;
        }

        #endregion

        #region Methods

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers))
                return AccessDeniedView();

            //prepare model
            var model = _customerRoleModelFactory.PrepareCustomerRoleSearchModel(new CustomerRoleSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(CustomerRoleSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _customerRoleModelFactory.PrepareCustomerRoleListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers) || !_permissionService.Authorize(StandardPermissionProvider.ManageAcl))
                return AccessDeniedView();

            //prepare model
            var model = _customerRoleModelFactory.PrepareCustomerRoleModel(new CustomerRoleModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(CustomerRoleModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers) || !_permissionService.Authorize(StandardPermissionProvider.ManageAcl))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var customerRole = model.ToEntity<CustomerRole>();
                _customerService.InsertCustomerRole(customerRole);

                //activity log
                _customerActivityService.InsertActivity("AddNewCustomerRole",
                    string.Format(_localizationService.GetResource("ActivityLog.AddNewCustomerRole"), customerRole.Name), customerRole);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Customers.CustomerRoles.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = customerRole.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = _customerRoleModelFactory.PrepareCustomerRoleModel(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers) || !_permissionService.Authorize(StandardPermissionProvider.ManageAcl))
                return AccessDeniedView();

            //try to get a customer role with the specified id
            var customerRole = _customerService.GetCustomerRoleById(id);
            if (customerRole == null)
                return RedirectToAction("List");

            //prepare model
            var model = _customerRoleModelFactory.PrepareCustomerRoleModel(null, customerRole);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Edit(CustomerRoleModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers) || !_permissionService.Authorize(StandardPermissionProvider.ManageAcl))
                return AccessDeniedView();

            //try to get a customer role with the specified id
            var customerRole = _customerService.GetCustomerRoleById(model.Id);
            if (customerRole == null)
                return RedirectToAction("List");

            try
            {
                if (ModelState.IsValid)
                {
                    if (customerRole.IsSystemRole && !model.Active)
                        throw new NopException(_localizationService.GetResource("Admin.Customers.CustomerRoles.Fields.Active.CantEditSystem"));

                    if (customerRole.IsSystemRole && !customerRole.SystemName.Equals(model.SystemName, StringComparison.InvariantCultureIgnoreCase))
                        throw new NopException(_localizationService.GetResource("Admin.Customers.CustomerRoles.Fields.SystemName.CantEditSystem"));

                    if (NopCustomerDefaults.RegisteredRoleName.Equals(customerRole.SystemName, StringComparison.InvariantCultureIgnoreCase) &&
                        model.PurchasedWithProductId > 0)
                        throw new NopException(_localizationService.GetResource("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Registered"));

                    customerRole = model.ToEntity(customerRole);
                    _customerService.UpdateCustomerRole(customerRole);

                    //activity log
                    _customerActivityService.InsertActivity("EditCustomerRole",
                        string.Format(_localizationService.GetResource("ActivityLog.EditCustomerRole"), customerRole.Name), customerRole);

                    _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Customers.CustomerRoles.Updated"));

                    return continueEditing ? RedirectToAction("Edit", new { id = customerRole.Id }) : RedirectToAction("List");
                }

                //prepare model
                model = _customerRoleModelFactory.PrepareCustomerRoleModel(model, customerRole, true);

                //if we got this far, something failed, redisplay form
                return View(model);
            }
            catch (Exception exc)
            {
                _notificationService.ErrorNotification(exc);
                return RedirectToAction("Edit", new { id = customerRole.Id });
            }
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers) || !_permissionService.Authorize(StandardPermissionProvider.ManageAcl))
                return AccessDeniedView();

            //try to get a customer role with the specified id
            var customerRole = _customerService.GetCustomerRoleById(id);
            if (customerRole == null)
                return RedirectToAction("List");

            try
            {
                _customerService.DeleteCustomerRole(customerRole);

                //activity log
                _customerActivityService.InsertActivity("DeleteCustomerRole",
                    string.Format(_localizationService.GetResource("ActivityLog.DeleteCustomerRole"), customerRole.Name), customerRole);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.Customers.CustomerRoles.Deleted"));

                return RedirectToAction("List");
            }
            catch (Exception exc)
            {
                _notificationService.ErrorNotification(exc.Message);
                return RedirectToAction("Edit", new { id = customerRole.Id });
            }
        }

        public virtual IActionResult AssociateProductToCustomerRolePopup()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageCustomers) || !_permissionService.Authorize(StandardPermissionProvider.ManageAcl))
                return AccessDeniedView();

            //prepare model
            var model = _customerRoleModelFactory.PrepareCustomerRoleProductSearchModel(new CustomerRoleProductSearchModel());

            return View(model);
        }

        [HttpPost]

nopCommerce_4.20_Source/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/AssociateProductToCustomerRolePopup.cshtml
@model CustomerRoleProductSearchModel

@{
    Layout = "_AdminPopupLayout";
    
    //page title
    ViewBag.Title = T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Choose").Text;
}

<form asp-controller="CustomerRole" asp-action="AssociateProductToCustomerRolePopup"
      asp-route-productIdInput="@Context.Request.Query["productIdInput"]"
      asp-route-productNameInput="@Context.Request.Query["productNameInput"]"
      asp-route-btnId="@Context.Request.Query["btnId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Choose")
        </h1>
        <div class="pull-right">
            &nbsp;
        </div>
    </div>

    @if (ViewBag.RefreshPage == true)
    {
        <script>
            try {
                window.opener.document.getElementById('@(Context.Request.Query["productIdInput"])').value = '@(ViewBag.productId)';
                window.opener.document.getElementById('@(Context.Request.Query["productNameInput"])').innerHTML = '@(ViewBag.productName)';
                window.opener.document.getElementById('@(Context.Request.Query["btnId"])').click();
            }
            catch (e){}
            window.close();
        </script>
    }
    else
    {

        <input type="hidden" asp-for="AddProductToCustomerRoleModel.AssociatedToProductId" />
        <div class="content">
            <div class="form-horizontal">
                <div class="panel-group">
                    <div class="panel panel-default panel-search panel-popup">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <div class="col-sm-5">
                                            <nop-label asp-for="SearchProductName" />
                                        </div>
                                        <div class="col-sm-7">
                                            <nop-editor asp-for="SearchProductName" />
                                        </div>
                                    </div>
                                    <div class="form-group" @(Model.AvailableCategories.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                        <div class="col-sm-5">
                                            <nop-label asp-for="SearchCategoryId" />
                                        </div>
                                        <div class="col-sm-7">
                                            <nop-select asp-for="SearchCategoryId" asp-items="Model.AvailableCategories" />
                                        </div>
                                    </div>
                                    <div class="form-group" @(Model.AvailableVendors.SelectionIsNotPossible() || Model.IsLoggedInAsVendor ? Html.Raw("style='display: none;'") : null)>
                                        <div class="col-sm-5">
                                            <nop-label asp-for="SearchVendorId" />
                                        </div>
                                        <div class="col-sm-7">
                                            <nop-select asp-for="SearchVendorId" asp-items="Model.AvailableVendors" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                        <div class="col-sm-5">
                                            <nop-label asp-for="SearchStoreId" />
                                        </div>
                                        <div class="col-sm-7">
                                            <nop-select asp-for="SearchStoreId" asp-items="Model.AvailableStores" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-5">
                                            <nop-label asp-for="SearchProductTypeId" />
                                        </div>
                                        <div class="col-sm-7">
                                            <nop-select asp-for="SearchProductTypeId" asp-items="Model.AvailableProductTypes" />
                                        </div>
                                    </div>
                                    <div class="form-group" @(Model.AvailableManufacturers.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                                        <div class="col-sm-5">
                                            <nop-label asp-for="SearchManufacturerId" />
                                        </div>
                                        <div class="col-sm-7">
                                            <nop-select asp-for="SearchManufacturerId" asp-items="Model.AvailableManufacturers" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <button type="button" id="search-products" class="btn btn-primary btn-search">
                                        <i class="fa fa-search"></i>
                                        @T("Admin.Common.Search")
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @await Html.PartialAsync("Table", new DataTablesModel
                            {
                                Name = "products-grid",
                                UrlRead = new DataUrl("AssociateProductToCustomerRolePopupList", "CustomerRole", null),
                                SearchButtonId = "search-products",
                                Length = Model.PageSize,
                                LengthMenu = Model.AvailablePageSizes,
                                Filters = new List<FilterParameter>
                                {
                                    new FilterParameter(nameof(Model.SearchProductName)),
                                    new FilterParameter(nameof(Model.SearchCategoryId)),
                                    new FilterParameter(nameof(Model.SearchManufacturerId)),
                                    new FilterParameter(nameof(Model.SearchStoreId)),
                                    new FilterParameter(nameof(Model.SearchVendorId)),
                                    new FilterParameter(nameof(Model.SearchProductTypeId))
                                },
                                ColumnCollection = new List<ColumnProperty>
                                {
                                    new ColumnProperty(nameof(ProductModel.Id))
                                    {
                                        Title = T("Admin.Common.Select").Text,
                                        Render = new RenderCustom("renderColumnSelectProduct"),
                                        ClassName =  NopColumnClassDefaults.Button,
                                        Width = "50",
                                    },
                                    new ColumnProperty(nameof(ProductModel.Name))
                                    {
                                        Title = T("Admin.Catalog.Products.Fields.Name").Text
                                    },
                                    new ColumnProperty(nameof(ProductModel.Published))
                                    {
                                        Title = T("Admin.Catalog.Products.Fields.Published").Text,
                                        Width = "100",
                                        ClassName = NopColumnClassDefaults.CenterAll,
                                        Render = new RenderBoolean()
                                    }
                                }
                            })
                            <script>
                                function renderColumnSelectProduct(data, type, row, meta) {
                                    return '<button type="button" onclick="selectAssociatedProduct(' + row.Id + ' )" class="btn btn-default">@T("Admin.Common.Select")</button>';
                                }
                                function selectAssociatedProduct(productid) {
                                    $("#@Html.IdFor(model => model.AddProductToCustomerRoleModel.AssociatedToProductId)").val(productid);
                                    $('#save').click();
                                }
                            </script>
                        </div>
                        <div class="panel-footer">
                            <button type="submit" id="save" name="save" class="btn btn-default" style="display: none">
                                @T("Admin.Common.Save")
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
</form>

nopCommerce_4.20_Source/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/Create.cshtml
@model CustomerRoleModel

@{
    //page title
    ViewBag.Title = T("Admin.Customers.CustomerRoles.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Customer roles");
}

<form asp-controller="CustomerRole" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Customers.CustomerRoles.AddNew") 
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Customers.CustomerRoles.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CustomerRoleDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

nopCommerce_4.20_Source/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/Edit.cshtml
@model CustomerRoleModel

@{
    //page title
    ViewBag.Title = T("Admin.Customers.CustomerRoles.EditCustomerRoleDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Customer roles");
}

<form asp-controller="CustomerRole" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Customers.CustomerRoles.EditCustomerRoleDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Customers.CustomerRoles.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="customerrole-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CustomerRoleDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="customerrole-delete" />

nopCommerce_4.20_Source/src/Presentation/Nop.Web/Areas/Admin/Views/CustomerRole/_CreateOrUpdate.cshtml
@model CustomerRoleModel

<div asp-validation-summary="ModelOnly"></div>
<input asp-for="Id" type="hidden" />

<script>
    $(document).ready(function() {
        $("#@Html.IdFor(model => model.OverrideTaxDisplayType)").click(toggleTaxDisplayType);
        toggleTaxDisplayType();

        toggleRemoveButton();
    });
    
    function toggleTaxDisplayType() {
        if ($('#@Html.IdFor(model => model.OverrideTaxDisplayType)').is(':checked')) {
            $('#pnlDefaultTaxDisplayType').show();
        } else {
            $('#pnlDefaultTaxDisplayType').hide();
        }
    }

    function toggleRemoveButton() {
        if ($('#@Html.IdFor(model => model.PurchasedWithProductId)').val() > 0) {
            $('#purchased-with-product-name-remove').show();
        } else {
            $('#purchased-with-product-name-remove').hide();
        }
    }
</script>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CustomerRoleDetailsTop, additionalData = Model })
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="Name" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="Name" asp-required="true" />
                            <span asp-validation-for="Name"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="Active" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="Active" />
                            <span asp-validation-for="Active"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="FreeShipping" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="FreeShipping" />
                            <span asp-validation-for="FreeShipping"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="TaxExempt" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="TaxExempt" />
                            <span asp-validation-for="TaxExempt"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="OverrideTaxDisplayType" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="OverrideTaxDisplayType" />
                            <span asp-validation-for="OverrideTaxDisplayType"></span>
                        </div>
                    </div>
                    <nop-nested-setting asp-for="OverrideTaxDisplayType">
                        <div class="form-group" id="pnlDefaultTaxDisplayType">
                            <div class="col-md-3">
                                <nop-label asp-for="DefaultTaxDisplayTypeId" />
                            </div>
                            <div class="col-md-9">
                                <nop-select asp-for="DefaultTaxDisplayTypeId" asp-items="Model.TaxDisplayTypeValues" />
                                <span asp-validation-for="DefaultTaxDisplayTypeId"></span>
                            </div>
                        </div>
                    </nop-nested-setting>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="EnablePasswordLifetime" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="EnablePasswordLifetime" />
                            <span asp-validation-for="EnablePasswordLifetime"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="PurchasedWithProductId" />
                        </div>
                        <div class="col-md-9">
                            <input type="hidden" asp-for="PurchasedWithProductId" />
                            <span id="purchased-with-product-name">@Model.PurchasedWithProductName</span>
                            <span asp-validation-for="PurchasedWithProductId"></span>
                            <button type="submit" onclick="javascript:OpenWindow('@(Url.Action("AssociateProductToCustomerRolePopup", "CustomerRole", new {productIdInput = Html.IdFor(model => model.PurchasedWithProductId), productNameInput = "purchased-with-product-name", btnId = "btnRefreshPurchasedWithProduct"}))', 800, 850, true); return false;" class="btn btn-primary">
                                @T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Choose")
                            </button>
                            <button type="submit" id="purchased-with-product-name-remove" class="btn bg-red">
                                @T("Admin.Customers.CustomerRoles.Fields.PurchasedWithProduct.Remove")
                            </button>
                            <input type="submit" id="btnRefreshPurchasedWithProduct" style="display: none" />

                            <script>
                                $(document).ready(function () {
                                    $('#purchased-with-product-name-remove').click(function () {
                                        $('#purchased-with-product-name').text('');
                                        $("#@Html.IdFor(model => model.PurchasedWithProductId)").val(0);
                                        toggleRemoveButton();
                                        //return false to don't reload a page
                                        return false;
                                    });

                                    $('#btnRefreshPurchasedWithProduct').click(function () {
                                        toggleRemoveButton();

                                        //return false to don't reload a page
                                        return false;
                                    });
                                });
                            </script>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="IsSystemRole" />
                        </div>
                        <div class="col-md-9">
                            <div class="form-text-row">@T(Model.IsSystemRole ? "Admin.Common.Yes" : "Admin.Common.No")</div>
                            <input type="hidden" asp-for="IsSystemRole" />
                            <span asp-validation-for="IsSystemRole"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            <nop-label asp-for="SystemName" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="SystemName" />
                            <span asp-validation-for="SystemName"></span>
                        </div>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.CustomerRoleDetailsBottom, additionalData = Model })
        </div>
    </div>
</div>